import type { Metadata } from "next";
import {DM_Sans} from 'next/font/google'
import "./globals.css";
import Header from "@/components/AppLayout/Header";
import Footer from "@/components/AppLayout/Footer";

const DmSans = DM_Sans({
  display: 'swap',
})

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${DmSans.className} antialiased`}
      >
        <Header />
        <main className="pt-12">{children}</main>
        <Footer />
      </body>
    </html>
  );
}
